version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test_linux:
    parameters:
      ruby_version:
        description: "version tag for the veracross/circleci-ruby-freetds container"
        type: string

    docker:
      - image: veracross/circleci-ruby-freetds:latest
      - image: metaskills/mssql-server-linux-tinytds:2017-GA

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: restore gem cache
          keys:
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-
            - v1-bundle-<< parameters.ruby_version >>-

      - run:
          name: install dependencies
          command: |
            bundle check --path ./vendor/bundle || bundle install --jobs=3 --retry=3 --path vendor/bundle
            bundle clean

      - save_cache:
          name: save gem cache
          paths:
            - ./vendor/bundle
          key: v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}

      - run:
          name: build gem
          command: |
            bundle exec rake build

      - run:
          # imported from setup.sh, although we should do better...
          name: wait for database
          command: |
            sleep 10

      - run:
          name: run tests
          command: |
            TINYTDS_UNIT_HOST=localhost bundle exec rake test

  cross_build:
    parameters:
      ruby_version:
        description: "version tag for the veracross/circleci-ruby-freetds container"
        type: string

    docker:
      - image: veracross/circleci-ruby-freetds:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: restore gem cache
          keys:
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-
            - v1-bundle-<< parameters.ruby_version >>-

      - run:
          name: install dependencies
          command: |
            bundle check --path ./vendor/bundle || bundle install --jobs=3 --retry=3 --path vendor/bundle
            bundle clean

      - save_cache:
          name: save gem cache
          paths:
            - ./vendor/bundle
          key: v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}

      - setup_remote_docker:
          version: 20.10.2

      - run:
          name: cross build gem
          command: |
            bundle exec rake gem:windows

      - persist_to_workspace:
          root: .
          paths:
            - .

  test_windows:
    parameters:
      ruby_version:
        description: "version tag for the veracross/circleci-ruby-freetds container"
        type: string

    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - run: systeminfo

      - run: pwd

      - checkout

      - restore_cache:
          name: restore gem cache
          keys:
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-
            - v1-bundle-<< parameters.ruby_version >>-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=3 --retry=3 --path ./vendor/bundle
            bundle clean

      - save_cache:
          name: save gem cache
          paths:
            - ./vendor/bundle
          key: v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}

      - run:
          # imported from setup.sh, although we should do better...
          name: wait for database
          command: |
            sleep 10

      - run:
          name: run tests
          command: |
            TINYTDS_UNIT_HOST=localhost bundle exec rake test

workflows:
  test_supported_ruby_versions:
    jobs:
      # - test_linux:
      #     matrix:
      #       parameters:
      #         ruby_version:
      #           - '2.5.3'
      #           - '2.7'

      - cross_build:
          matrix:
            parameters:
              ruby_version:
                - '2.5.3'
                - '2.7'

      - test_windows:
          requires:
            - cross_build
          matrix:
            parameters:
              ruby_version:
                - '2.5.3'
                - '2.7'
