version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  test_linux:
    parameters:
      ruby_version:
        description: "version tag for the veracross/circleci-ruby-freetds container"
        type: string

    docker:
      - image: veracross/circleci-ruby-freetds:latest
      - image: metaskills/mssql-server-linux-tinytds:2017-GA

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: restore gem cache
          keys:
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-
            - v1-bundle-<< parameters.ruby_version >>-

      - run:
          name: install dependencies
          command: |
            bundle check --path ./vendor/bundle || bundle install --jobs=3 --retry=3 --path vendor/bundle
            bundle clean

      - save_cache:
          name: save gem cache
          paths:
            - ./vendor/bundle
          key: v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}

      - run:
          name: build gem
          command: |
            bundle exec rake build

      - run:
          # imported from setup.sh, although we should do better...
          name: wait for database
          command: |
            sleep 10

      - run:
          name: run tests
          command: |
            TINYTDS_UNIT_HOST=localhost bundle exec rake test

  test_windows:
    parameters:
      ruby_version:
        description: "version tag for the veracross/circleci-ruby-freetds container"
        type: string

    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - run:
          name: diagnostics
          command: |
            systeminfo
            pwd
            perl --version
            ruby --version
            gem --version

      - run:
          # https://www.msys2.org/news/#2020-06-29-new-packagers
          name: prepare msys2- update keyring
          command: |
            C:\msys64\usr\bin\curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
            C:\msys64\usr\bin\curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
            ridk exec bash -c "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
            ridk exec bash -c "pacman -U --noconfirm --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"

      - run:
          # https://github.com/msys2/MSYS2-packages/issues/2300
          name: prepare msys2- update zstd and pacman first
          command: |
            C:\msys64\usr\bin\pacman --noconfirm --upgrade https://repo.msys2.org/msys/x86_64/zstd-1.4.7-1-x86_64.pkg.tar.xz # Must come First, or else pacman will install 1.4.8
            C:\msys64\usr\bin\pacman --noconfirm --upgrade https://repo.msys2.org/msys/x86_64/pacman-5.2.2-5-x86_64.pkg.tar.xz

      - run:
          name: prepare msys2- update packages
          command: |
            C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade

      - run:
          # Kill all running msys2 binaries to avoid error "size of shared memory region changed".
          # See https://github.com/msys2/MSYS2-packages/issues/258
          name: prepare msys2- stop processes
          command: |
            powershell -Command "Get-Process | Where-Object {$_.path -like 'C:\msys64*'} | Stop-Process"

      - run:
          # prevent freetds to link to wrong ws2_32 lib on i686-w64-mingw32
          name: prepare msys2- avoid linking to wrong package
          command: |
            c:/msys64/usr/bin/rm /usr/lib/w32api/libws2_32.a

      - checkout

      - restore_cache:
          name: restore gem cache
          keys:
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}
            - v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-
            - v1-bundle-<< parameters.ruby_version >>-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=3 --retry=3 --path ./vendor/bundle
            bundle clean

      - save_cache:
          name: save gem cache
          paths:
            - ./vendor/bundle
          key: v1-bundle-<< parameters.ruby_version >>-{{ .Branch }}-{{ checksum "tiny_tds.gemspec" }}

      - run:
          name: install ports
          command: |
            bundle exec rake ports

      - run:
          name: build gem
          command: |
            bundle exec rake build

      - run:
          # imported from setup.sh, although we should do better...
          name: wait for database
          command: |
            sleep 10

      - run:
          name: run tests
          command: |
            TINYTDS_UNIT_HOST=localhost bundle exec rake test

workflows:
  test_supported_ruby_versions:
    jobs:
      # - test_linux:
      #     matrix:
      #       parameters:
      #         ruby_version:
      #           - '2.5.3'
      #           - '2.7'


      - test_windows:
          matrix:
            parameters:
              ruby_version:
                # - '2.5.3'
                - '2.7'
